insert into public.products (
  id,
  name,
  slug,
  short_description,
  description,
  price_label,
  price_per_kg,
  category,
  featured,
  available,
  image_url,
  gallery_images,
  sort_order,
  whatsapp_message
)
values
  (
    'f4e7ae2e-9c5b-4a23-a21f-a8f0f05f0101',
    'Kaab Lghzal',
    'kaab-lghzal',
    'Delicate crescent pastries filled with roasted almond paste and orange blossom.',
    'A signature Moroccan favourite shaped by hand and finished with a gentle dusting of sugar. Our Kaab Lghzal balances buttery pastry with fragrant almond filling for refined gifting and elegant tea tables.',
    null,
    90,
    'Kaab Lghzal',
    true,
    true,
    '/images/products/kaab-lghzal.svg',
    array['/images/products/kaab-lghzal.svg', '/images/products/kaab-lghzal-detail.svg'],
    1,
    'Hello, I would like to order Kaab Lghzal.'
  ),
  (
    'f4e7ae2e-9c5b-4a23-a21f-a8f0f05f0102',
    'Chebakia',
    'chebakia',
    'Honey-glazed sesame pastries with a festive golden finish.',
    'Braided and folded with care, our Chebakia is glazed in honey and showered with toasted sesame for a rich texture and deeply comforting Ramadan tradition.',
    null,
    55,
    'Chebakia',
    true,
    true,
    '/images/products/chebakia.svg',
    array['/images/products/chebakia.svg'],
    2,
    'Hello, I would like to order Chebakia.'
  ),
  (
    'f4e7ae2e-9c5b-4a23-a21f-a8f0f05f0103',
    'Ghriba',
    'ghriba',
    'Tender Moroccan cookies with a crackled finish and buttery melt.',
    'Our Ghriba is baked for a soft interior and a lightly crisp edge, making it ideal for coffee service, family visits, and elegant assorted boxes.',
    null,
    48,
    'Ghriba',
    false,
    true,
    '/images/products/ghriba.svg',
    array['/images/products/ghriba.svg'],
    3,
    'Hello, I would like to order Ghriba.'
  ),
  (
    'f4e7ae2e-9c5b-4a23-a21f-a8f0f05f0104',
    'Almond Briwat',
    'almond-briwat',
    'Crisp triangle pastries layered with almond filling and honey shine.',
    'Thin pastry is folded by hand around spiced almond paste, then baked to a crisp finish and brushed with warm honey. A refined choice for weddings and premium mixed assortments.',
    null,
    72,
    'Briwat',
    true,
    true,
    '/images/products/almond-briwat.svg',
    array['/images/products/almond-briwat.svg'],
    4,
    'Hello, I would like to order Almond Briwat.'
  ),
  (
    'f4e7ae2e-9c5b-4a23-a21f-a8f0f05f0105',
    'Sellou',
    'sellou',
    'Aromatic toasted flour blend with almonds, sesame, and warming spice.',
    'Traditionally prepared for Ramadan and celebrations, our Sellou is rich, nourishing, and deeply aromatic. It is presented in a premium serving jar or gift-ready container.',
    null,
    36,
    'Sellou',
    false,
    true,
    '/images/products/sellou.svg',
    array['/images/products/sellou.svg'],
    5,
    'Hello, I would like to order Sellou.'
  ),
  (
    'f4e7ae2e-9c5b-4a23-a21f-a8f0f05f0106',
    'Assorted Gift Box',
    'assorted-gift-box',
    'A curated premium selection presented for gifting and celebrations.',
    'An elegant assortment of our finest handmade pastries, styled for hosting, gifting, corporate gestures, and special occasions. Each box is arranged with balance, colour, and generosity in mind.',
    'From 28 EUR / box',
    null,
    'Gift Boxes',
    true,
    true,
    '/images/products/assorted-gift-box.svg',
    array['/images/products/assorted-gift-box.svg', '/images/products/assorted-gift-box-detail.svg'],
    6,
    'Hello, I would like to order the Assorted Gift Box.'
  )
on conflict (id) do nothing;
